### ISSUE TITLE
Opção Sinalização linha amarela

### ISSUE THREAD

**Issue by duartepbrandao** [jfoclpf/form-for-parking-violation#127]
Olá.

Digam-me se não for o melhor sitio para expor esta situação pois não é exclusivamente técnica.
Antes de mais, obrigado por desenvolverem esta app.

Através do seu uso deparei-me com a seguinte situação com a PM do Porto. Enviei uma denuncia de um carro estacionado num local exclusivamente sinalizado com a linha continua na berma (M12). 

O problema é que embora esta infração esteja prevista no 62º artigo do Regulamento de Sinalização do Trânsito‐ DR‐22/A/98, atualizado pelo DR6/2019 de 22OUT, não existe uma sanção correspondente a esta infração no 65º artigo, pelo que a policia não pode autuar.

**Comment by jfoclpf** [comment]
olá Duarte, é uma pergunta jurídica, a qual confesso não sei a resposta, mas tentarei saber

https://www.reddit.com/r/portugal/comments/ry6awz/algu%C3%A9m_que_perceba_do_c%C3%B3digo_da_estrada_me_pode/

https://forum.mubi.pt/t/alguem-que-perceba-do-codigo-da-estrada-me-pode-ajudar-com-esta-pergunta-muito-agradecido/9780

**Comment by jfoclpf** [comment]
@duartepbrandao 

vê [isto](https://www.e-konomista.pt/fiscais-multar-ou-rebocar-carro-na-linha-amarela/): 

> Dantas Rodrigues: Os fiscais da Câmara Municipal podem levantar autos de contraordenação aos carros indevidamente estacionados, uma vez que o Código da Estrada prevê a competência das Câmaras Municipais para o efeito.
> 
> O estacionamento em linha amarela constitui contraordenação, nos termos do art.º 62.º, do Regulamento da Sinalização de Trânsito e é sancionado entre 24,94€ e 124,70€.
> 
> É uma contraordenação leve punida apenas com coima.
> 
> Porém existe uma área delimitada por linhas contínuas de cor amarela, onde é permitido a paragem e estacionamento apenas para efetuar cargas e descargas. (M14A)

**Comment by jfoclpf** [comment]
@duartepbrandao estiver a ver melhor e parece que de facto a PM tem razão, se o artigo 65º (sanções) não contempla a linha M12, de facto acho que a polícia não pode autuar.

**Comment by duartepbrandao** [comment]
Pois, foi à conclusão que cheguei assim pela leitura desses pontos.
Ou seja, é como se não existisse sinalização. 🤷 

Eu estava a avisar porque vocês têm essa opção, mas sendo assim nunca dará resultado.

**Comment by jfoclpf** [comment]
Parece que esse artigo 65º originalmente incluía a M12, ora [vê aqui](https://dre.pt/dre/legislacao-consolidada/decreto-regulamentar/1998-169035729-169039300).

Mas parece que deixou de incluir na [versão atual](https://files.dre.pt/1s/2019/12/24501/0000200175.pdf), não percebo se foi erro ou algo propositado.

**Comment by duartepbrandao** [comment]
Já chegamos a essa conclusão então que o legislador se enganou e a M12 se tornou inválida.

Será que esta opção e relacionadas (tinha que comparar todas as opções relacionadas com a M12 e M12a) devem ser tiradas da lista de opções enquanto que a legislação não corrige o erro?

**Comment by jfoclpf** [comment]
É boa ideia, não vale a pena estar na lista de infrações uma infração que não tem moldura sancionatória.

Podes enviar um e-mail à ANSR a perguntar por que motivo estas infrações não têm sanção? Estou um bocado queimado junto da ANSR :) Para não pensarem que é sempre o mesmo chato.
