### ISSUE TITLE
Falta de tipo de denuncia

### ISSUE THREAD

**Issue by manmacedo** [jfoclpf/form-for-parking-violation#129]
Falta de uma infração das mais básicas que é "proibido parar e estacionar" e proibido estacionar". Obrigado

**Comment by jfoclpf** [comment]
Proibido estacionar é muito vago, é preciso contexto e base legal

**Comment by manmacedo** [comment]
Boa tarde,

Tentando ser mais claro:

Na APP falta 2 das proibições mais básicas relativas a infracoes de
estacionamento, como sendo as infracções  dos:

Artigo 49.º relativo à proibição de paragem e estacionamento. Regulado pelo
sinal rodoviário C16

Artigo 71.º relativo à proibição de estacionamento. Regulado pelo Sinal
rodoviário C15


Espero ter ajudado a contribuir para a melhoria da aplicação.

Com os meus cumprimentos
Miguel Macedo
966184996

A qua, 26 de jan de 2022, 15:10, João Pimentel Ferreira <
***@***.***> escreveu:

> Proibido estacionar é muito vago, é preciso contexto e base legal
>

**Comment by duartepbrandao** [comment]
Olá,

Criei estes casos.

https://github.com/jfoclpf/form-for-parking-violation/pull/130

**Comment by jfoclpf** [comment]
@duartepbrandao e @manmacedo obrigados

sabem se o Regulamento de Sinalização do Trânsito prevê coimas?

**Comment by jfoclpf** [comment]
@duartepbrandao e @manmacedo já foram introduzidas essas anomalias, ora vede
https://github.com/jfoclpf/form-for-parking-violation/blob/master/www/json/penalties.json#L107

Também já está na APP em produção na Play Store
obrigados
