### ISSUE TITLE
Duas entidades, para o mesmo concelho

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/form-for-parking-violation#13]
Enviar a duas ou mais entidades, para o mesmo concelho, por exemplo PSP e Polícia Municipal.

`<a href='mailto:person1@domain.com,person2@domain.com'>Email Us</a>`

**Comment by dfgarcia** [comment]
não sei se é boa ideia. 
1º uma das que recebe pode ignorar por não ter a responsabilidade das multas de estacionamento ou
2º serem emitidas 2 contra-ordenações

**Comment by jfoclpf** [comment]
Bem visto. Vou alterar em conformidade.

Em 26/07/2017 2:06 PM, "dfgarcia" <notifications@github.com> escreveu:

**Comment by jfoclpf** [comment]
Não enviar a duas entidades para evitar eventual duplicação de coimas.

Simplesmente, quando para o mesmo concelho, há duas entidades, como por exemplo Aveiro ou Bragança, até porque estas entidades têm domínios distintintos, normalmente uma na cidade, e a outra fora da cidade, colocar duas opções e deixar o utilizador escolher qual entidade contactar.

**Comment by jfoclpf** [comment]
resolvido com o código em [js/localization.js](https://github.com/jfoclpf/form-for-parking-violation/blob/master/js/localization.js)
