### ISSUE TITLE
Sugestão: Anexar foto automaticamente

### ISSUE THREAD

**Issue by PedroRCSequeira** [jfoclpf/form-for-parking-violation#14]
A ideia seria poder selecionar uma photo, e nas opções tipo guardar na drive, partilhar whatsapp, etc, aparecia a app
Ao aceder à app os dados data, hora, conselho, arruamento, morada e número podiam ficar automaticamente preenchidos usando os dados gps da foto (mas editáveis just in case

O gerar texto criava logo um email com a foto respectiva anexada, e enviava automaticamente assim que tivessemos net (assim para tirar a foto bastava ligar o gps para os dados

**Comment by jfoclpf** [comment]
São muitas coisas numa só tarefa :)
Em qualquer caso estou neste momento a desenvolver a parte da foto na app fazendo uso da estrutura que o Rui desenvolveu.
