### ISSUE TITLE
Gps

### ISSUE THREAD

**Issue by fmscorreia60** [jfoclpf/form-for-parking-violation#140]
Ultimamente aparece sempre o Concelho de Oeiras, estando eu em Espinho. A app tem todas as permissões.

**Comment by aritabrito** [comment]
Estou com o mesmo problema em Android.
A rua é detectada, mas o concelho não.

**Comment by jfoclpf** [comment]
@aritabrito mas também está em Espinho?

**Comment by fmscorreia60** [comment]
Basta abrir a app, aparece logo Concelho de Oeiras. Eu estou em Espinho

**Comment by jfoclpf** [comment]
Se reparar Oeiras é apenas um exemplo sugestivo. Se escrever desaparece logo.

Em qualquer caso para não gerar confusão vou alterar isso.

**Comment by fmscorreia60** [comment]
João, certo.
Mas anteriormente aparecia automaticamente a localização correcta.
Muito obrigado

**Comment by jfoclpf** [comment]
Já vi onde está o problema

O serviço de geolocalização mudou de domínio para geoapi.pt

Preciso de atualizar aqui

https://github.com/jfoclpf/form-for-parking-violation/blob/master/www/js/main.js#L39

**Comment by fmscorreia60** [comment]
Temos de actualizar a app?

Obrigado, feliz Natal

**Comment by jfoclpf** [comment]
Depois sim

**Comment by aritabrito** [comment]
Desculpa, mas só vi agora. Não, estou no Porto.

**Comment by jfoclpf** [comment]
resolvido na versão 2.9.0

**Comment by fmscorreia60** [comment]
João,

Rua 12 está certo, Concelho de Oeiras...

**Comment by jfoclpf** [comment]
@fmscorreia60 já atualizaste para a v 2.9.0? Já está bem?

Não percebi a tua última mensagem

**Comment by fmscorreia60** [comment]
João,

Bom dia, está impecável, mas tive que actualizar manualmente. Isto é um s22
ultra.

Muito obrigado por tudo
Abraço

**Comment by jfoclpf** [comment]
Fixe

Resto de bom dia
