### ISSUE TITLE
Dropdown tipo de ocorrência permite seleção múltipla

### ISSUE THREAD

**Issue by aritabrito** [jfoclpf/form-for-parking-violation#141]
O formulário `Tipo de Ocorrência` permite que sejam selecionadas várias opções mas, pelo menos a Polícia Municipal do Porto, descarta as denúncias quando mais do que um tipo é selecionado.

Neste caso, a solução é fazer duas denúncias separadamente quando se verifica mais do que uma infracção.

**Comment by jfoclpf** [comment]
Bem-visto, ou seja, abrir vários emails consoante o número de infrações, cada email com uma denúncia separada?

**Comment by jfoclpf** [comment]
resolvido

**Comment by jfoclpf** [comment]
olá @aritabrito , muito obrigados pela participação

pensando bem eu não tenho forma de saber quando deve ser enviada duas infrações na mesma denúncia ou em duas denúncias diferentes, porque tal depende de cada polícia. Terá de ser o utilizador a fazer essa decisão, enviando duas denúncias
