### ISSUE TITLE
Sugestão: Possibilidade de guardar rascunhos

### ISSUE THREAD

**Issue by aritabrito** [jfoclpf/form-for-parking-violation#142]
Era bom poder ter a possibilidade de guardar rascunhos para, por exemplo, guardar a ocorrência quando ocorre um erro na assinatura digital. Desta forma, seria possível continuar com outras denúncias e retomar mais tarde.

**Comment by jdanielcmedina** [comment]
A ideia é boa, mas deve ter duração, na minha opinião o "auto" tem que ser gerado na hora.

**Comment by jfoclpf** [comment]
lamento meus caros, mas tal envolveria muito trabalho desnecessário
