### ISSUE TITLE
Can't upload picture

### ISSUE THREAD

**Issue by Lisboanoite** [jfoclpf/form-for-parking-violation#146]
Camera and media permissions are never requested, thus uploading a picture doesn't work.

The option to provide said permissions is also not available in the the specific Android setting. Only location shows up there.

Pixel 5 Android 13

**Comment by jfoclpf** [comment]
Do you mean adding a photo from the media gallery or when adding photo
directly from the camera?

A terça, 31/01/2023, 22:06, Lisboanoite ***@***.***> escreveu:

**Comment by jfoclpf** [comment]
É um problema do plugin da câmara que não funciona ainda em Android 13


https://github.com/apache/cordova-plugin-camera/issues/797

Estão a tratar disso

**Comment by Lisboanoite** [comment]
Like I said, both permissions missing. Can't upload in any manner.

**Comment by jfoclpf** [comment]
it's a problem related withe the camera plugin (Google changed permission settings in Android 13), we will have to wait

**Comment by jfoclpf** [comment]
Testar este PR
```
cordova plugin add https://github.com/apache/cordova-plugin-camera.git#pull/814/master
```

**Comment by jfoclpf** [comment]
Solved with new version.

Please test and tell me if it works
