### ISSUE TITLE
Para aumentar o rigor da denúncia, usar web time API

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/form-for-parking-violation#148]
https://stackoverflow.com/a/75529987/1243247

**Comment by froque** [comment]
https://oal.ul.pt/hora-legal/como-acertar/

**Comment by jfoclpf** [comment]
> https://oal.ul.pt/hora-legal/como-acertar/

obrigado pela dica @froque mas eu preciso para client side javascript; esta APP está desenvolvida em Javascript

**Comment by jfoclpf** [comment]
feito
