### ISSUE TITLE
Quanto é demasiado?

### ISSUE THREAD

**Issue by parenthetical** [jfoclpf/form-for-parking-violation#149]
No meu bairro em Lisboa poderia gerar uma quantidade incrível de denúncias todos os dias. É nojento como as pessoas têm de andar na estrada para ir a qualquer lugar por causa de passeios bloqueadas.

Então, alguem sabe o que aconteceria se eu denunciasse cada um deles cada dia? (Não que teria tempo para fazer tantos.)

**Comment by jfoclpf** [comment]
Experimente denunciar eles todos, a APP é totalmente gratuita, não tem
limite de utilização, garanta apenas que denuncia um de cada vez. Pode
fazer vários no mesmo dia, experimente também denunciar a policias
diferentes

A segunda, 13/03/2023, 23:33, Adriaan Leijnse ***@***.***>
escreveu:

**Comment by parenthetical** [comment]
Obrigado pela resposta. Vou ver o que acontece!
