### ISSUE TITLE
Imagem do texto gerado no google play

### ISSUE THREAD

**Issue by dfgarcia** [jfoclpf/form-for-parking-violation#15]
Não sei se os dados que aparecem na imagem serão mesmo teus, se não forem ignora isto. Muitas pessoas agradecem a ideia da app como se pode comprovar pelas mais de 7500 partilhas do artigo da NIT, mas muitas outras, neste momento, odeiam-te por tudo na vida (talvez estas até sejam mais) se os dados são reais recomendo-te trocar por fictícios.

**Comment by jfoclpf** [comment]
De facto, foi um lapso meu, e sim os dados são meus, mas estão incompletos e errados. Estou emigrado na Holanda :) Não habito em PT. E agora nada posso fazer porque a imagem já consta na notícia da NIT. Já agora, como sabes o número de partilhas da NIT? Não vejo lá nada. Mas sim, vou alterar a imagem do texto gerado no google play.

**Comment by dfgarcia** [comment]
"como sabes o número de partilhas da NIT"

Acho que foi a ti que respondi no FB. Não são partilhas da publicação que o NIT fez no FB mas sim o total de partilhas que foram feitas do artigo do site da NIT. Na pesquisa do FB procurei pelo titulo da noticia.

https://scontent.flis8-2.fna.fbcdn.net/v/t1.0-9/20476349_10210035117009826_5102213076762122059_n.jpg?oh=abd8f7aee8f49fe57d00b6a1645b3607&oe=5A029AEC

na altura deste printscreen tinha 7614 partilhas

**Comment by jfoclpf** [comment]
Obrigado

João Pimentel Ferreira <http://joãopimentel.eu>

2017-07-29 1:08 GMT+02:00 dfgarcia <notifications@github.com>:

**Comment by jfoclpf** [comment]
resolvido, mudei a imagem do google play
