### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by vantunes** [jfoclpf/form-for-parking-violation#152]
Tentei ajudar um tio meu a utilizar a APP no iPhone e a APP da um erro de "Não foram encontrados para as autoridades para este código postal" 
O código postal introduzido é o 6230-339.
Pode verificar o que se passa com a APP na versão apple.
Obrigado
Continuação de um bom trabalho

**Comment by jfoclpf** [comment]
não percebo, a que código postal se refere, se a APP não pede nenhum código postal

**Comment by jfoclpf** [comment]
não percebo a que erro se refere
