### ISSUE TITLE
Suportar Android 10

### ISSUE THREAD

**Issue by bolach** [jfoclpf/form-for-parking-violation#153]
Estou a tentar instalar pelo PlayStore num Redmi 9 com android 10, mas diz que a APP não é compativel com o meu dispositivo. Existe algum APK para instalação manual?

**Comment by jfoclpf** [comment]
Devido a vários motivos de compatibilidade deixámos de suportar Android 10

**Comment by bolach** [comment]
> Devido a vários motivos de compatibilidade deixámos de suportar Android 10

Obrigado pela informação

**Comment by jfoclpf** [comment]
Em qualquer caso vou na próxima versão suportar Android 10 e vamos ver como corre.

Não o fiz pois já sei o que a casa gasta, basta que alguma cena não funcione e é logo o utilizador a dar nota 1.

Fica atento a esta issue

**Comment by bolach** [comment]
Obrigado. Se precisares de algum tipo de teste avisa.

**Comment by jfoclpf** [comment]
Obrigado, sim, talvez vá precisar

**Comment by jfoclpf** [comment]
em princípio será apenas preciso alterar esta linha
https://github.com/jfoclpf/form-for-parking-violation/blob/master/config.xml#L35
para value `29` (Android 10 (API level 29))
https://developer.android.com/tools/releases/platforms

**Comment by jfoclpf** [comment]
@bolach já tentei que fosse compatível com Android 10, diga se funciona do seu lado
deverá esperar pela versão 2.9.2

**Comment by jfoclpf** [comment]
confirme ainda que a parte da câmara/foto está a funcionar

**Comment by bolach** [comment]
> @bolach já tentei que fosse compatível com Android 10, diga se funciona do seu lado deverá esperar pela versão 2.9.2

Ok, testarei quando sair

**Comment by jfoclpf** [comment]
recebi agora a mensagem, já saiu, confirme apenas que é a versão 2.9.2

João Pimentel Ferreira <https://www.joaopimentel.com>

**Comment by jfoclpf** [comment]
fixe, obrigado pelo retorno 

o mail vai estar sempre na caixa de emails enviados, e para colocar um CC teria que pedir também o email, que levantaria suspeitas com RGPD (atencao que nenhuns dos dados pessoais sao guardados em BD, fica tudo apenas no dispositivo)

vou entao fechar o tópico
se entretanto surgir algum outro problema diz ou cria outro issue

**Comment by DamienC5** [comment]
Novo update: Huawei P20 Pro, Android 10, resolvido! Obrigado.

**Comment by DamienC5** [comment]
Comentei na publicação:“Novo update: Huawei P20 Pro, Android 10, resolvido! Obrigado.”Tudo a funcionar muito bem.Obrigado. Abraço! De: João Pimentel FerreiraEnviado: 26 de maio de 2023 09:37Para: jfoclpf/form-for-parking-violationCc: DamienC5; ManualAssunto: Re: [jfoclpf/form-for-parking-violation] Suportar Android 10 (Issue #153) Closed #153 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
