### ISSUE TITLE
Sinalização em falta

### ISSUE THREAD

**Issue by FilipeOS** [jfoclpf/form-for-parking-violation#154]
Boa tarde, podiam adicionar ocorrência de "carro não elétrico estacionado em local para carregamento elétrico"?

Também, carro em carga ou estacionado em local sinalizado mas com dístico em falta?

E, carro elétrico estacionado mas não em carga?

Estas 3 são legais, multas aplicáveis e estão em falta. Acontecem aos potes

**Comment by jfoclpf** [comment]
O primeiro caso já existe

https://github.com/jfoclpf/form-for-parking-violation/blob/master/www/json/penalties.json#L52

Tens base legal para os outros? Sem base legal nada pode ser feito.

**Comment by jfoclpf** [comment]
Já agora, se vires que falta alguma ocorrência, podes editar tu próprio esse ficheiro, mas tens de ter base legal.

**Comment by FilipeOS** [comment]
Será isto? https://eportugal.gov.pt/servicos/pedir-o-distico-identificativo-para-veiculos-eletricos

https://www.acp.pt/eletricos/tudo-sobre-eletricos/conduzir-um-eletrico/detalhe/distico-de-veiculos-eletricos-o-que-e-e-para-que-serve ?

**Comment by FilipeOS** [comment]
Basicamente a lei diz que, para usar o estacionamento de carro elétrico "em carga" o veiculo além de elétrico tem de ter o distico azul. Sem distico azul, até um eletrico normal pode ser multado.

Distico azul = Circulação nas vias públicas ou equiparadas E Identificação e usufruto de mecanismos de discriminação positiva de veículos elétricos, designadamente para efeitos de estacionamento

**Comment by FilipeOS** [comment]
Acho que a alteração mais fácil será "Lugar de veículo elétrico / Dístico em falta"

**Comment by jfoclpf** [comment]
Acho que deves adicionar uma ocorrência nova para distinguir simplesmente dos carros que não são elétricos. Caso contrário vai criar confusão na polícia pois o código da estrada não menciona dístico azul.

Qual a base legal para o caso da ausência do dístico azul?

**Comment by jfoclpf** [comment]
@FilipeOS isto é para enviar às polícias, sem base legal (da infração e respectiva coima), não posso adicionar nada, porque a mensagem deixa de ter valor jurídico e passa a ser inútil.

Caso encontres base legal depois posso reabrir o tópico

**Comment by jfoclpf** [comment]
ver por exemplo #143 por que motivo a base legal para a infração e respectiva coima é essencial
