### ISSUE TITLE
Zona de escolas 

### ISSUE THREAD

**Issue by MRosle** [jfoclpf/form-for-parking-violation#156]
Bom dia.

Seria possível acrescentar a opção de estacionamento indevido nas zonas próprias para parar e entregar alunos nas zonas escolares? Aquelas com bolas azuis pintadas no chão. Obrigado.

**Comment by jfoclpf** [comment]
Olá, sabe me dizer qual a base legal à luz do código da estrada?

Basta depois editar este ficheiro em conformidade 

https://github.com/jfoclpf/form-for-parking-violation/blob/master/www/json/penalties.json

**Comment by jfoclpf** [comment]
ver por exemplo #143 por que motivo a base legal para a infração e respectiva coima é essencial
