### ISSUE TITLE
Deploye iOS app in other Apple stores

### ISSUE THREAD

**Issue by canales** [jfoclpf/form-for-parking-violation#157]
I tried downloading the iOS app however it said it was not available in my store (I am linked to the US one, but live in PT). I will do the switch to the PT store, but thought it would be good to have it in other stores to be able to have more people using it (tourists, erasmus students, etc. who often down own a car).

**Comment by jfoclpf** [comment]
@worm69

**Comment by jfoclpf** [comment]
Hi @canales one of the reasons we don't provide for other countries is because the app just works in Portugal, which may lead users to install the app by mistake frustrating them later on since the app doesn't work outside of Portugal

**Comment by worm69** [comment]
Thanks @canales for suggestion but as @jfoclpf  said app doesn't work outside of Portugal

**Comment by canales** [comment]
Gotcha, that makes sense and more now that I see that you need a "chave digital". Kudos for producing this app, but Im perplexed at how bureaucratic the cities' process are. 

Do you have any aggregate statistics about the number of reports over time, by type and maybe location? I work on urban/transport planning stuff and believe this info would be good for a large journalistic piece (Lisboa para pessoas) or maybe a a kind of ranking amongst municipios (as a way to put pressure on the public sector to do more active enforcement).

**Comment by jfoclpf** [comment]
Hi @canales I will close this issue because we won't make the app available to other regions, since the app only works in Portugal. If you have further issues feel free to open another issues. Thanks
