### ISSUE TITLE
Salvar dados pessoais on focusout

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/form-for-parking-violation#16]
Neste momento os dados pessoais são guardados apenas quando o utilizador clica Gerar Texto

Guardar dados pessoais logo em cada .onfocusout dos campos

**Comment by dfgarcia** [comment]
se conseguir ter tempo esta semana agarro nisso

**Comment by jfoclpf** [comment]
Obrigados :)
Se tiveres dúvidas a usar o Apache Cordova diz, aquilo é um pouco complexo
ao início.
