### ISSUE TITLE
A sua Aplicação

### ISSUE THREAD

**Issue by humanitarian11** [jfoclpf/form-for-parking-violation#161]
Você não faz ideia do mau estar que esta aplicação vai causar no meio de comunidades, e de como pessoas mal-intencionadas a vão usar para fazer mal a outras pessoas. A sua intenção talvez tenha sido inicialmente boa, com a questão dos passeios e lugares para deficientes, mas a evolução tornou esta aplicação em algo maléfico e negativo. Você foi inteligente o suficiente para criar uma aplicação, mas não para antever os perigos que dela advêm.

**Comment by jfoclpf** [comment]
offtopic
