### ISSUE TITLE
Nova categoria de carros abandonados ou largados em estacionamentos em estado de avançada degradação, criando problemas de higiene pública.

### ISSUE THREAD

**Issue by Ruirei77** [jfoclpf/form-for-parking-violation#163]
No conteúdo actual apenas se verifica há mais de 30 dias no mesmo local, o que muitas situações são mais graves sendo o abandono (independente da razão) estes veiculos provocam situações de pleno atentado á higiene pública.

**Comment by jfoclpf** [comment]
aquela situação fos 30 dias tem base legal, sem base legal para o que pretende não há nada a fazer
