### ISSUE TITLE
Add a new violation line

### ISSUE THREAD

**Issue by PeraRocha** [jfoclpf/form-for-parking-violation#167]
Must have a violation line for "parking in emergency vehicle access"

**Comment by jfoclpf** [comment]
Para que essa sugestão possa avançar, tem sempre que providenciar base
legal à luz do Código da Estrada.

Qual o artigo e número do Código da Estrada?

Depois só tens que editar este ficheiro, é muito fácil

https://github.com/jfoclpf/form-for-parking-violation/blob/master/www/json/penalties.json
