### ISSUE TITLE
Incluir um alerta para falsas declarações 

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/form-for-parking-violation#17]
O crime de falsas declarações passa a abranger todas as afirmações feitas perante as autoridades oficiais, que se destinem a produzir efeitos jurídicos, próprios ou alheios, e punido com pena de prisão até um ano ou de multa, se a pena mais grave “não lhe couber por força de outra disposição legal”.
A nova redacção do artigo 348 define, na alínea a), que "quem declarar ou atestar falsamente à autoridade pública, ou a funcionário no exercício das suas, identidade, estado ou outra qualidade a que a lei atribua efeitos jurídicos, próprios ou alheios, é punido com pena de prisão até um ano ou com pena de multa, se pena mais grave não lhe couber por força de outra disposição legal".

https://www.publico.pt/2013/02/21/sociedade/noticia/crime-de-falsas-declaracoes-sujeito-a-pena-de-prisao-ate-um-ano-1585280

**Comment by jfoclpf** [comment]
Código Penal

Artigo 348.º-AFalsas declarações

1 - Quem declarar ou atestar falsamente à autoridade pública ou a funcionário no exercício das suas funções identidade, estado ou outra qualidade a que a lei atribua efeitos jurídicos, próprios ou alheios, é punido com pena de prisão até um ano ou com pena de multa, se pena mais grave não lhe couber por força de outra disposição legal. 
2 - Se as declarações se destinarem a ser exaradas em documento autêntico o agente é punido com pena de prisão até dois anos ou com pena de multa.»
--

http://www.pgdlisboa.pt/leis/lei_mostra_articulado.php?ficha=301&artigo_id=&nid=109&pagina=4&tabela=leis&nversao=&so_miolo=

**Comment by dfgarcia** [comment]
como achas que se deve mostrar esse aviso?

**Comment by jfoclpf** [comment]
Logo a seguir aos **dados da ocorrência**

![image](https://user-images.githubusercontent.com/3984909/29037662-d1b717b0-7ba4-11e7-920d-b64325638440.png)

A frase deverá ser:

**Ao abrigo do artigo 348.º-A do Código Penal, quem declarar ou atestar falsamente à autoridade pública, como um agente policial no exercício das suas funções, identidade ou outra qualidade a que a lei atribua efeitos jurídicos nos demais cidadãos, é punido com pena de prisão até um ano ou com pena de multa.**
