### ISSUE TITLE
Perda de tempo, sem chave móvel 

### ISSUE THREAD

**Issue by EduardoVB1974** [jfoclpf/form-for-parking-violation#171]
Sem chave móvel não é possível fazer a denúncia apesar de ser enviado por email com toda a nossa identificação para a PSP respectiva. Porquê?

**Comment by EduardoVB1974** [comment]
A PSP não dá seguimento

**Comment by EduardoVB1974** [comment]
Porquê?

**Comment by jfoclpf** [comment]
Tal é claro na app, sem chave móvel digital deve dirigir-se à esquadra para
a qual envia a denúncia, para se identificar presencialmente junto das
autoridades. Tal é explícito no parecer emitido pela ANSR.

Cumprimentos

**Comment by EduardoVB1974** [comment]
Devo ir sem me chamarem? A que esquadra?
O email gerado pela app diz:

"Pode-se comprovar esta situação através da fotografia anexa à presente mensagem eletrónica. Juro pela minha honra que a informação supra citada é verídica. Recordo ainda, que ao abrigo do referido n.º 5 do artigo 170.º do Código da Estrada, a autoridade que tiver notícia por denúncia de contraordenação, levanta auto, não carecendo de presenciar tal contraordenação rodoviária, situação a que se aplica o n.º 1 do mesmo artigo. Refiro ainda que me encontro plenamente disponível para participar na qualidade de testemunha no processo que vier a ser instaurado com referência à presente missiva."

**Comment by jfoclpf** [comment]
Não pode enviar para o email geral da PSP, terá que enviar directamente
para uma esquadra ou polícia municipal, dizendo que está disponível para se
identificar presencialmente.

João Pimentel Ferreira <https://www.joaopimentel.com>

**Comment by EduardoVB1974** [comment]
A app preenche o email automaticamente
spm@cm-maia.pt
Polícia Municipal
Mas não me chamam e informam que não vão dar seguimento, pura e simplesmente

**Comment by EduardoVB1974** [comment]
Resposta da polícia municipal:

**Comment by EduardoVB1974** [comment]
Não solicitam que vá a lado algum

**Comment by jfoclpf** [comment]
Insista com eles

**Comment by EduardoVB1974** [comment]
Neste país de.... compensa ser uma.....

**Comment by EduardoVB1974** [comment]
Já insisti com 17 reenvios
