### ISSUE TITLE
Chave móvel digital não funciona 

### ISSUE THREAD

**Issue by MelissaCr** [jfoclpf/form-for-parking-violation#172]
Bom dia, hoje estava a tentar submeter uma denúncia, no entanto não consigo assinar o documento com a chave móvel digital. O código sms para avançar com a assinatura não é enviado, carreguei umas 10 vezes no botão para enviar o código e ele não envia nada, depois de meia hora a tentar desisti

**Comment by jfoclpf** [comment]
a AMA estava em baixo, já está a funcionar
