### ISSUE TITLE
Adicionar mais concelhos

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/form-for-parking-violation#18]
-Leiria
-Benavente
-Lagos

**Comment by jfoclpf** [comment]
-Faro
-Odivelas

**Comment by dfgarcia** [comment]
Enviei email à cm de gaia e leiria a pedir o email da pm e vou ver se envio às outras

**Comment by dfgarcia** [comment]
Lagos o contacto da policia é lagos.faro@psp.pt
Benavente O site da GNR fornece o email ct.str.dcch.pbnv@gnr.pt (não percebo este tipo de escolha de email)
Leiria: a esquadra de transito da PSP não tem email publico, mas a esquadra normal tem este: esquadrasede.leiria@psp.pt (deve-se usar o da esquadra, divisão de transito ou comando distrital?)
Faro: só o comando distrital é que tem email publico cpfaro@psp.pt
Odivelas: não encontrei nada
Almada: esquadra de transito divalmada.setubal@psp.pt

**Comment by dfgarcia** [comment]
obtive resposta da p.m de gaia:  pm@mail.cm-gaia.pt

**Comment by jfoclpf** [comment]
Vim agora da Google Play, a malta pede:
-Matosinhos
-Setúbal
-Portimão
-Almada

**Comment by dfgarcia** [comment]
pedi à cm de Matosinhos o email da pm
PSP Setúbal: stbesqtr@psp.pt
PSP Portimão: divportimao.faro@psp.pt
PSP Almada: divalmada.setubal@psp.pt

**Comment by dfgarcia** [comment]
mo. Senhor,
 
Acusamos a receção do e-mail infra, o qual mereceu a nossa melhor atenção.
 
Informamos V. Exª que a Polícia Municipal partilha o mesmo e-mail da Câmara de Matosinhos; qualquer pedido/participação é encaminhado ao respetivo serviço.
 
Contudo, seguem mais contactos:
 
Polícia Municipal / Proteção Civil
Rua 1º de Maio, 273
229 398 560
229 388 818
Secretaria: 9h às 20h – 2ª feira a 6ª feira
Brigadas: 7h às 02h00
Telefone de Emergência: 800 208 545
 
 
Os serviços da Loja do Munícipe estarão sempre ao vosso dispor para qualquer esclarecimento.
 
Com os melhores cumprimentos,


mail@cm-matosinhos.pt

**Comment by dfgarcia** [comment]
adicionados ao ficheiros

**Comment by jfoclpf** [comment]
Obrigados :)

**Comment by portugaldev** [comment]
Estou a fazer uma lista de contactos: 

https://docs.google.com/spreadsheets/d/11hD9AJ8oLfflR5EoELYGS-iHv17Q8pdZkIprrj8g0h0/edit?usp=sharing

**Comment by jfoclpf** [comment]
Excelente, mas como deverá ser feita essa divisão? Não seria melhor por concelhos?
Como está o seu ficheiro em Java? A sintaxe não é mesma que esta? https://github.com/jfoclpf/form-for-parking-violation/blob/master/js/municipalities.js

**Comment by portugaldev** [comment]
Já adicionei também os contactos da PSP.
Eu estou a usar SQLite. Mas facilmente se gera um JSON a partir das tabelas.
A minha duvida é em relação à seleção das autoridades.

Devemos preferir a PSP à GNR? Devemos preferir uma esquadra de transito da PSP? Devemos preferir um posto de transito da GNR?

**Comment by dfgarcia** [comment]
depende bastante da freguesia, mas normalmente o esquema é PSP na cidade, GNR em meios mais rurais

**Comment by jfoclpf** [comment]
Fiz aqui um excel com os municípios do país:
https://docs.google.com/spreadsheets/d/1d9pUTegqp1cGj6hGOMvjdjuGp0UmdYrRkQSf9W8G6FY/edit?usp=sharing
Acho que poderíamos editar este excel. Que vos parece?

**Comment by portugaldev** [comment]
Então, por exemplo Almancil, concelho de Loulé, distrito de Faro, há as seguintes possibilidades:
- Posto Territorial de Almancil - ct.far.dlle.palc@gnr.pt
- Destacamento Territorial de Loulé - ct.far.dlle@gnr.pt
- Destacamento de Trânsito de Faro - ct.far.tfar@gnr.pt
- Comando Territorial de Faro - ct.far@gnr.pt
- Unidade Nacional de Trânsito - unt@gnr.pt
- Comando Geral da Guarda Nacional Republicana - gnr@gnr.pt
- Faro - Divisão Policial - div.faro@psp.pt
- Faro - Comando Distrital - cpfaro@psp.pt

Quais é que são validos, ou preferiveis?

Poderiamos por exemplo enviar sempre para a Unidade Nacional de Trânsito?

**Comment by jfoclpf** [comment]
Considerando que Faro é já outro concelho, e que Almancil é apenas
freguesia, diria que o válido é este: Destacamento Territorial de Loulé

**Comment by jfoclpf** [comment]
mudou-se o código, considerando a tabela que o @portugaldev forneceu. 
ver funções em [js/localization.js](https://github.com/jfoclpf/form-for-parking-violation/blob/master/js/localization.js)
Agora dá para o país todo!
