### ISSUE TITLE
Autenticação chave móvel digital não funciona

### ISSUE THREAD

**Issue by gisulan** [jfoclpf/form-for-parking-violation#186]
A autenticação com chave móvel digital não está a funcionar, da um erro "Server Unavailable". A URL que está a usar é https://cmd.autenticacao.gov.pt/Ama.Authentication.Frontend/Processes/DigitalSignature/DigitalSignatureIntro.aspx.
Podem validar o erro na imagem anexa.
![Screenshot_20241010_210329_com android chrome](https://github.com/user-attachments/assets/95cd5650-3d1c-466a-ac82-4a2472dd4532)

**Comment by jfoclpf** [comment]
Esse serviço é providenciado pelo governo (AMA) e o site da AMA está em
baixo

https://www.ama.gov.pt/

aparentemente foi alvo de ataque

https://observador.pt/2024/10/10/agencia-para-a-modernizacao-administrativa-alvo-de-ciberataque-servicos-como-a-chave-movel-digital-atingidos/

**Comment by jfoclpf** [comment]
Já está funcional
