### ISSUE TITLE
Estacionamento em lugar deficientes 

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/form-for-parking-violation#20]
Artigo 145 código da estrada
https://dre.pt/web/guest/home/-/dre/107648315/details/maximized

**Comment by portugaldev** [comment]
Não se aplica o artigo 50?

http://www.bomcondutor.pt/biblioteca/codigo-estrada#50

1 - É proibido o estacionamento:
f) Nos locais reservados, mediante sinalização, ao estacionamento de determinados veículos;

**Comment by jfoclpf** [comment]
A alínea q) do artigo 145 é muito mais explícita, mas julgo que tens razão,
essa também se aplica

Já agora, uma pergunta, como fazes a partir do GPS para obter o concelho?
Alguma ideia?

**Comment by portugaldev** [comment]
https://developers.google.com/maps/documentation/javascript/geocoding#ReverseGeocoding

**Comment by jfoclpf** [comment]
Corrigir
>Escrevo-vos devido a uma denúncia que fiz de um carro estacionado em lugar de deficientes. A resposta da PM de Lisboa é que " a legislação arrolada não se enquadra com os factos verificados na foto". Depois de algumas trocas de e-mails com um agente a resposta dele em relação ao artigo 145º é que "Conforme informa e muito bem, o artº 145º do CE, apenas clarifica quais são as infracções graves." 
Após leitura do CE enviei nova denúncia usando a alínea f) do n.º 1 do art.º 50 (Proibição de estacionamento): " f) Nos locais reservados, mediante sinalização, ao estacionamento de determinados veículos;"

**Comment by jfoclpf** [comment]
Já está resolvido
