### ISSUE TITLE
Violações do artigo 71 do código da estrada.

### ISSUE THREAD

**Issue by rubenrebelo** [jfoclpf/form-for-parking-violation#55]
Estes dois tipos de violação em particular não se encontram tipificados nas denúncias:

1 - Nos parques e zonas de estacionamento é proibido estacionar:
a) Veículos destinados à venda de quaisquer artigos ou a publicidade de qualquer natureza;
b) Automóveis pesados utilizados em transporte público, quando não estejam em serviço, salvas as exceções previstas em regulamentos locais;

**Comment by jfoclpf** [comment]
Muito obrigados por relatar a falha. Pode apenas dar-nos a base legal, ou seja, os artigos do CdE?

**Comment by rubenrebelo** [comment]
![Screenshot_20200528-143956128](https://user-images.githubusercontent.com/4621416/83148667-28c84f00-a0f1-11ea-99f5-c7f672abb7c4.jpg)

Aqui vai.

**Comment by jfoclpf** [comment]
Caro @rubenrebelo , obrigados pelo retorno, o código já foi atualizado e sairá na próxima versão.
