### ISSUE TITLE
Novo contacto PM de Olhão 

### ISSUE THREAD

**Issue by NelsonFarroba** [jfoclpf/form-for-parking-violation#74]
Já existe Polícia Municipal na cidade de Olhão.
O seu contacto é policiamunicipal@cm-olhao.pt e o número de telefone é o 289700150

**Comment by jfoclpf** [comment]
Obrigados, será atualizado na próxima versão

**Comment by jfoclpf** [comment]
Obrigado @NelsonFarroba é só acrescentar no ficheiro
https://github.com/jfoclpf/form-for-parking-violation/blob/master/www/js/contacts.js
logo ao início ao array `app.contacts.PM_Contacts = [`
Fá-lo-ei ASAP

**Comment by jfoclpf** [comment]
Na boa @NelsonFarroba eu adiciono o quanto antes e sai na próxima versão

**Comment by NelsonFarroba** [comment]
Obrigado, agradeço imenso, excelente trabalho de sua parte.

A sexta, 5/02/2021, 9:17 PM, João Pimentel Ferreira <
notifications@github.com> escreveu:

**Comment by jfoclpf** [comment]
@NelsonFarroba a PM de Olhão foi adicionada com b85a48d149b70bfc89ba846ec1556a956c2875d1

Agora é só esperar que faça o deploy para a Play Store

agradecido

**Comment by NelsonFarroba** [comment]
Muito obrigado João Ferreira. Cumprimentos Nelson Farroba De: João Pimentel FerreiraEnviado: 1 de março de 2021 11:06 AMPara: jfoclpf/form-for-parking-violationCc: NelsonFarroba; MentionAssunto: Re: [jfoclpf/form-for-parking-violation] Novo contacto PM de Olhão (#74) @NelsonFarroba a PM de Olhão foi adicionada com b85a48dAgora é só esperar que faça o deploy para a Play Storeagradecido—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
