### ISSUE TITLE
Deploy para iOS

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/form-for-parking-violation#76]
Aluguei um serviço macOS na nuvem para poder compilar corretamente para iOS e estive nos últimos dias a remover plugins desnecessários e a atualizar outros para compilar corretamente para iOS.

Assim terá que se fazer
```
git clone https://github.com/jfoclpf/form-for-parking-violation.git
cd form-for-parking-violation
cordova platform add ios
cd platforms/ios
pod update
open Denúncia\ Estacionamento.xcworkspace/
```

Em princípio as instruções acima funcionam por si só.

## `cordova build ios`

Contudo não é possível fazer `cordova build ios` pois o plugin OCR (para as matrículas) não está a funcionar de forma automática em iOS (ver [aqui](https://www.npmjs.com/package/cordova-plugin-mobile-ocr#installation-steps)).

**Comment by worm69** [comment]
@jfoclpf já podemos fechar este tópico?

**Comment by jfoclpf** [comment]
Sim, mais uma vez muito obrigados ;)
