### ISSUE TITLE
seria possivel criar também um site para além da app

### ISSUE THREAD

**Issue by froque** [jfoclpf/form-for-parking-violation#90]
Pessoalmente sou maior fã de usar um computador para preencher os detalhes da ocorrência, assinar o PDF e enviar. O telemóvel usaria apenas para tirar fotografias. 

Uma vez que o código é sobretudo HTML, CSS e JS não deveria ser muito dificil.

**Comment by jfoclpf** [comment]
sim, é possível e em tempos fi-lo, mas tinha muitos erros, como por exemplo tirar foto ou mesmo a deteção automática do local e por isso descontinuei essa versão.

**Comment by jfoclpf** [comment]
em qualquer caso uma versão para iOS está mesmo prestes a sair e por isso julgo que não haverá necessidade de uma versão web.
