### ISSUE TITLE
Local da ocorrência é sempre actualizado depois de mudar de aplicação

### ISSUE THREAD

**Issue by froque** [jfoclpf/form-for-parking-violation#93]
Para reproduzir:
 - alterar manualmente o local da ocorrência
 - mudar de aplicação
 - voltar à aplicação da Denúncia de Estacionamento
 - o local da ocorrência foi alterado para o local onde está o telemóvel, pelas coordenadas GPS
 
Um dos sitios onde isto se manifesta é no titulo do email, depois de assinar o PDF noutra aplicação.

**Comment by jfoclpf** [comment]
Muito obrigado @froque 
vamos trabalhar nisso ASAP

**Comment by jfoclpf** [comment]
foi resolvido com o 31051860b0001ffe28ed8b11618f27a11f4eec44
ficará operacional assim que fizer o build para a play store, agradecidos pelo retorno
