### ISSUE TITLE
Não se consegue ler o texto todo nas infrações em iOS

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/form-for-parking-violation#94]
![image](https://user-images.githubusercontent.com/3984909/115405809-e028f100-a1ee-11eb-9a4b-40b454627ba9.png)

@worm69 vês Daniel, eu disse-te que ia começar o pessoal a queixar-se, mas é bom, é sinal que estão a usar :)

**Comment by worm69** [comment]
@jfoclpf criticas é sempre bem vindas se forem validas. Já tens alguma ideia para a resolução? Não sei se da para por o texto a mexer para o lado deforma a ires lendo a descrição ou dar altura para duas linhas de texto por opção.
Pede lhe o modelo de iphone para termos ideia sff

**Comment by jfoclpf** [comment]
@worm69 o iOS tem uma forma estranha de mostrar HTML select boxes, quando chegar a casa vou ver, e sim, críticas válidas são sempre bem-vindas :)

**Comment by worm69** [comment]
@jfoclpf sabes como colocar os itens do picker para duas linhas? Por defeito é apenas usada uma 
![imagem](https://user-images.githubusercontent.com/12191069/115865665-8c0d4f00-a430-11eb-8bb3-a01d260b6fb3.png)

**Comment by jfoclpf** [comment]
Olá @worm69 tenho tido muito pouco tempo mas vejo isso sem falta hoje à noite. O problema é que para simular isso preciso sempre de uma máquina MacOS. Mas talvez no webbiew do Safari esse problema dê para replicar, fazendo `cordova run browser --debug`.

**Comment by jfoclpf** [comment]
@worm69 estive a investigar e parece não ser resolúvel do lado do Javascript
https://stackoverflow.com/questions/15390882/ios-picker-control-with-multi-line-items

Parece que é algo que está do lado dos ficheiros iOS, talvez tenhamos de adicionar flags ao `config.xml` como aquelas que fizemos para salvar os ficheiros PDF.

**EDIT**:
@worm69 vendo melhor, vi isto
https://stackoverflow.com/questions/19398154/how-to-fix-truncated-text-on-select-element-on-ios7

Vamos experimentar adicionar esta linha
```
  <optgroup label=""></optgroup>
```

**Comment by jfoclpf** [comment]
@worm69 não consegui testar pois editei o código diretamente do github pois não estou no meu PC, mas podes tentar agora? FIz esta alteração c604cc277e93a1e53eac60cda6adbf9263886aeb

**Comment by worm69** [comment]
@jfoclpf mais logo já testo no mac isso

**Comment by jfoclpf** [comment]
Olá Daniel, ainda não é desta pois estive a testar, mas já encontrei o problema, amanhã coloco isso a funcionar

![screenshot_12](https://user-images.githubusercontent.com/3984909/116012153-1cae7f80-a629-11eb-9077-83866195ad70.png)

**Comment by worm69** [comment]
Boa, eu ainda não tive tempo de testar a alteração mas quando fizeres de novo commit testo no iphone se

**Comment by jfoclpf** [comment]
Boas Daniel, já fiz as alterações necessárias e já testei no MacOS e está a funcionar. Também avancei uma versão para tu colocares lá na loja apple (agora está na 2.7.5). Está tudo no `master`. Depois testa sff e diz se deu bem do teu lado. Obrigado e um abraço

**Comment by worm69** [comment]
@jfoclpf já testei e esta ok já esta em processo na apple mas foi com a versão 2.7.7 por causa das rejeições tive de ir incrementando o valor

**Comment by jfoclpf** [comment]
Ótimo Daniel. Podes sff fazer PR dessas  alterações? Para estarmos sincronizados. Obrigado

**Comment by jfoclpf** [comment]
Olá Daniel, posso fechar este problema?

**Comment by worm69** [comment]
sim
