### ISSUE TITLE
Corrigir layout/sidebar em iPad

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/form-for-parking-violation#97]
![117283830-18bb0280-ae5e-11eb-8118-faac658119a6](https://user-images.githubusercontent.com/3984909/117285519-650b4000-ae68-11eb-973e-cac47e32661b.jpg)

Obrigado @worm69 , vou ver isso ASAP

Acho que consigo ver isso sem precisar de mac, pois o cordova também tem uma versão browser e basta alargar o tamanho da janela

**Comment by worm69** [comment]
ok, eu no email que te tinha mandado perguntei se o layout é a base de bootstrap ou css puro?

**Comment by jfoclpf** [comment]
é css /JS , está aqui

https://github.com/jfoclpf/form-for-parking-violation/blob/master/www/css/sidebar.css
https://github.com/jfoclpf/form-for-parking-violation/blob/master/www/js/sidebar.js

**Comment by jfoclpf** [comment]
Olá Daniel @worm69 
estive de férias, daí a demora.
Já resolvi esta questão com dfe46bf209b43c77c2bb18f6c5f528a895b59f1e
Podes por favor confirmar?

um abraço e obrigado

**Comment by worm69** [comment]
Olá @jfoclpf , Fizeste bem.
Esta semana ainda estou a dar aulas mas quarta feira já tenho tempo de testar e depois dou novidades.
Obrigado pela correção e um abraço

**Comment by jfoclpf** [comment]
Muito obrigado @worm69

**Comment by jfoclpf** [comment]
@worm69 isto sempre ficou resolvido?
Um abraço

**Comment by worm69** [comment]
@jfoclpf  só tive tempo de alterar agora, mas como é só meta dados segunda ou terça já devemos ter novidades

**Comment by jfoclpf** [comment]
Muitos obrigados @worm69 
Ficarei então à espera

**Comment by worm69** [comment]
@jfoclpf já foi aprovada e já esta na loja testei no iphone. Também respondi aos comentários

**Comment by jfoclpf** [comment]
Fixe 
Muito agradecido @worm69 
Um abraço 

Se entretanto surgirem mais problemas, abre aqui uma issue, é mais fácil tratar e gerir.
