### ISSUE TITLE
Falta de campo

### ISSUE THREAD

**Issue by Fake4522** [jfoclpf/form-for-parking-violation#99]
Quando fazemos a denúncia não podemos colocar a matrícula, no Android conseguia fazer, no iOS já não, está em falta o campo de matrícula, por favor vejam o que se passa, obrigado

**Comment by jfoclpf** [comment]
isso é uma exigência da Apple pois considerou que a matrícula era difamatório. Pode sempre colocar a matrícula no corpo do email. @worm69 podes esclarecer pf o OP? Agradecido

**Comment by worm69** [comment]
@Fake4522 Bateu neste ponto das guide lines deles, apesar de já ter visto outra app de ios com o campo matricula tivemos de retirar. Desculpa o acontecimento mas era isso ou não podíamos publicar novas correcções 
Guideline 1.1.1 - Safety - Objectionable Content


Your app includes content that could be considered defamatory or mean-spirited. Specifically, your app encourages users to report vehicle activity associated with specific license plates.

Next Steps

To resolve this issue, please remove all potentially defamatory and mean-spirited content from your app and submit your revised binary for review.
